# Hi I am an example config file. Modify me to suit your needs and copy me to "config.yml" to
# proceed.

# What port should we use?
port: 3030

# What GPIO pin is the servo hooked up to? Proper GPIO number, not the number of the physical pin
# location.
opto_gpio: 4 

# How long should we hold down the buzzer, in seconds?
opto_press_time: 2

# Enough servo crap. What's your Twilio Account_SID? It should look kind of like
# this: AC1caf3aeab2f5ec77318e376ad89cda9f
twilio_sid: ACbf164fd6149bf631e47e151fe3008e0d

# Finally: you don't want any random shlub to be able to open your door. What phone numbers should
# we respond to? In E.164 format, so the american 999-888-7777 becomes +19998887777. Add as many
# as you like!
number_whitelist:
  - "+13476680599"
  - "+12065019241"

# Cool you're done.
